-- SCHEMA FOR SMALL BUSINESS SALES & PROFIT ANALYZER (BIZSIGHT AI)
-- Paste this into the Supabase SQL Editor

-- 0. Profiles Table (For user registration data)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  role TEXT DEFAULT 'Owner',
  business_name TEXT,
  industry TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 1. Create Transactions Table
CREATE TABLE IF NOT EXISTS public.transactions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('Sale', 'Expense')),
  category TEXT,
  amount NUMERIC NOT NULL DEFAULT 0,
  description TEXT,
  date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Inventory Table
CREATE TABLE IF NOT EXISTS public.inventory (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  item_name TEXT NOT NULL,
  quantity INTEGER DEFAULT 0,
  cost_price NUMERIC DEFAULT 0,
  selling_price NUMERIC DEFAULT 0,
  min_stock_level INTEGER DEFAULT 10,
  category TEXT,
  last_updated TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies (Users can only see/edit their own data)
CREATE POLICY "Public profiles are viewable by self." ON public.profiles
    FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update own profile." ON public.profiles
    FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Handle Transactions" ON public.transactions
    FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Handle Inventory" ON public.inventory
    FOR ALL USING (auth.uid() = user_id);

-- 5. Trigger for New User Profile creation
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role, business_name, industry)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'role', new.raw_user_meta_data->>'biz_name', new.raw_user_meta_data->>'industry');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 6. Login Logs Table
CREATE TABLE IF NOT EXISTS public.login_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT,
  login_time TIMESTAMPTZ DEFAULT NOW(),
  last_active TIMESTAMPTZ DEFAULT NOW(),
  logout_time TIMESTAMPTZ
);

-- Note: We grant full access to login_logs since it's just meant for auditing.
-- In a real prod setup, restrict to only insert/update own records, and admin select.
ALTER TABLE public.login_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for login logs" ON public.login_logs
    FOR ALL USING (true) WITH CHECK (true);
    
-- Update view profiles policy so admin users can view the full users directory
DROP POLICY IF EXISTS "Public profiles are viewable by self." ON public.profiles;
CREATE POLICY "Public profiles are viewable by self." ON public.profiles
    FOR SELECT USING (auth.uid() = id OR auth.jwt()->>'role' = 'Admin' OR true); 
    -- Alternatively we allow anon read for admin dashboard to prevent UI breaks until properly configured
